--- #YAML:1.0
name:                Tree-Suffix
version:             0.15
abstract:            Perl interface to the libstree library.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - gray <gray@cpan.org>
