# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tree-Suffix
version:      0.01
version_from: lib/Tree/Suffix.pm
installdirs:  site
requires:
    Test::More:                    1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
